apis: []
versionSets: []
workspaces: []
backends: []
namedValues: []
products: []
subscriptions: []
tags: []
policyFragments:
 - fragment1
 - fragment2
groups: []
loggers: []
diagnostics: []
gateways: []